variable "zone" {
  type        = string
  description = "TC zone in which the network resources will be created"
  default     = "ru-central1-c"
}

variable "token" {
  type        = string
  description = "Yandex Cloud security OAuth token"
}

variable "folder_id" {
  type        = string
  description = "Yandex Cloud Folder ID where resources will be created"
}

variable "cloud_id" {
  type        = string
  description = "Yandex Cloud ID where resources will be created"
}

variable "bucket_name" {
  type        = string
  description = "Name for the Terraform remote state bucket"
}

variable "ydb_name" {
  type        = string
  description = "Name for the remote backend serverless ydb. Will be used for resource locking"
}

# variable "bucket_access_key" {
#   type        = string
#   description = <<EOF
# Value will be generated by main.tf: yandex_iam_service_account_static_access_key resource.
# Once the example instance is initialised and tf apply is done, then need to switch backend to remote.
# The value needs to be taken from terraform.tfsate file and provided as "bucket_access_key" eighter 
# as environmental variable or in .auto.tfvars file
# EOF
# }

# variable "bucket_secret_key" {
#   type        = string
#   description = <<EOF
# Value will be generated by main.tf: yandex_iam_service_account_static_access_key resource.
# Once the example instance is initialised and tf apply is done, then need to switch backend to remote.
# The value needs to be taken from terraform.tfsate file and provided as "bucket_secret_key" eighter 
# as environmental variable or in .auto.tfvars file
# EOF
# }
