variable "zone" {
  type        = string
  description = "TC zone in which the network resources will be created"
  default     = "ru-central1-c"
}

variable "token" {
  type        = string
  description = "Yandex Cloud security OAuth token"
}

variable "folder_id" {
  type        = string
  description = "Yandex Cloud Folder ID where resources will be created"
}

variable "cloud_id" {
  type        = string
  description = "Yandex Cloud ID where resources will be created"
}

variable "bucket_name" {
  type        = string
  description = "Name for the Terraform remote state bucket"
}

variable "ydb_name" {
  type        = string
  description = "Name for the remote backend serverless ydb. Will be used for resource locking"
}


### Group of backend.auto.tfvars variables
### The following varibles come from backend.auto.tfvars.
### This file is autogenerated as a result of terraform apply.
### The purpose of this file is to switch and work with remote 
### "s3' type backend for terraform state. 

variable "access_key" {
  type        = string
  description = "Belongs to 'backend.auto.tfvars' group"
}

variable "secret_key" {
  type        = string
  description = "Belongs to 'backend.auto.tfvars' group"
}

variable "bucket" {
  type        = string
  description = "Belongs to 'backend.auto.tfvars' group"
}

variable "dynamodb_endpoint" {
  type        = string
  description = "Belongs to 'backend.auto.tfvars' group"
}
