variable "token" {
  description = "Yandex Cloud security OAuth token"
}

variable "folder_id" {
  description = "Yandex Cloud Folder ID where resources will be created"
}

variable "cloud_id" {
  description = "Yandex Cloud ID where resources will be created"
}

variable "zone" {
  type        = string
  description = "TC zone in which the network resources will be created"
  default     = "ru-central1-c"
}

### Group of link_to_backend.auto.tfvars variables
### The following varibles come from file:
### link_to_backend.auto.tfvars --> ../remote-state/backend.auto.tfvars.
### ../remote-state/backend.auto.tfvars is autogenerated as a result of apply in remote-state module.
### The purpose of this vars is to work with remote backend for terraform state. 

variable "access_key" {
  type        = string
  description = "Belongs to 'backend.auto.tfvars' group"
}

variable "secret_key" {
  type        = string
  description = "Belongs to 'backend.auto.tfvars' group"
}

variable "bucket" {
  type        = string
  description = "Belongs to 'backend.auto.tfvars' group"
}

variable "dynamodb_endpoint" {
  type        = string
  description = "Belongs to 'backend.auto.tfvars' group"
}

variable "vm_name" {
  type        = string
  description = "Provide name of the virtual machine"
}

variable "image_family" {
  type        = string
  description = <<EOF
Please provide the name for the desired OS image. Examples: {
   debian-11
   ubuntu-1804-lts
   centos-7
   opensuse-15-3
}
EOF
}

variable "apache_package_name" {
  type        = string
  default     = "empty"
  description = <<EOF
Optional. Allows to provide apache webserver package name expicitly.
For Debian based distroes it is 'apache2', for Centos/RedHat/Fedora - 'httpd'.
If not provided, tf module will try to evaluate 'image_family' variable and
assign 'apache_package_name' correspondingly
EOF
}

variable "ssh_public_key" {
  type        = string
  description = "Provide ssh public key for remote access to webserver"
}
