variable "zone" {
  type        = string
  description = "TC zone in which the network resources will be created"
  default     = "ru-central1-c"
}

variable "vpc_name" {
  type        = string
  description = "Name for the custom vpc"
  default     = "my_vpc"
}

variable "subnet_name" {
  type        = string
  description = "Name for the subnet in custom vpc"
}

variable "subnet_cidrs" {
  type        = list(string)
  description = "Provide list of the cidr blocs for custom subnet. Example: [\"192.168.10.0/24\"]"
}

variable "token" {
  description = "Yandex Cloud security OAuth token"
}

variable "folder_id" {
  description = "Yandex Cloud Folder ID where resources will be created"
}

variable "cloud_id" {
  description = "Yandex Cloud ID where resources will be created"
}

### Group of link_to_backend.auto.tfvars variables
### The following varibles come from file:
### link_to_backend.auto.tfvars --> ../remote-state/backend.auto.tfvars.
### ../remote-state/backend.auto.tfvars is autogenerated as a result of apply in remote-state module.
### The purpose of this vars is to work with remote backend for terraform state. 

variable "access_key" {
  type        = string
  description = "Belongs to 'backend.auto.tfvars' group"
}

variable "secret_key" {
  type        = string
  description = "Belongs to 'backend.auto.tfvars' group"
}

variable "bucket" {
  type        = string
  description = "Belongs to 'backend.auto.tfvars' group"
}

variable "dynamodb_endpoint" {
  type        = string
  description = "Belongs to 'backend.auto.tfvars' group"
}
